zitadel:
  masterkey: 59Uv8buoCogfhghfghcwNcmxvuyBDLdb
  # masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalSecure: false
    ExternalDomain: auth.gsingh.io
    TLS:
      Enabled: false
    Database:
      Postgres:
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
  configSecretName: zitadel-config-secrets
  configSecretKey: config.yaml