apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL:  https://airflow.apache.org
    chart: airflow
    targetRevision: 1.15.0
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      selfHeal: true
