apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io/
    chart: authentik
    targetRevision: 2024.12.3
    helm:
      values: |
        authentik:
            error_reporting:
              enabled: true
            postgresql:
        server:
          ingress:
            enabled: true
            hosts:
              - auth2.gsingh.io
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
