apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/singh-gur/helm_charts.git
    path: charts/whoami
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true