apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-wf
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: {{.Values.argowf.version}}
    helm:
      values: |
        workflow:
          serviceAccount:
            create: true
            name: "argo-workflow"
          rbac:
            create: true
        controller:
          workflowNamespaces:
            - default
        server:
          authModes:
            - sso
          ingress:
            enabled: true
            hosts:
              - {{.Values.argowf.ingress.host}}
          sso:
            enabled: true
            issuer: {{.Values.argowf.sso.issuer}}
            clientId:
              name: argowf-secrets
              key: client-id
            clientSecret:
              name: argowf-secrets
              key: client-secret
            redirectUrl: {{.Values.argowf.sso.redirectUrl}}
            rbac:
              ebabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
