apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.coder.com/v2
    chart: coder
    targetRevision: 2.20.2
    helm:
      values: |
        coder:
          service:
            type: ClusterIP
          env:
            - name: CODER_ACCESS_URL
              value: "https://ide.gsingh.io"
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: coder-secrets
                  key: db-url
            - name: CODER_OIDC_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: coder-secrets
                  key: oidc-issuer-url
            - name: CODER_OIDC_EMAIL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: coder-secrets
                  key: oidc-email-domains
            - name: CODER_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: coder-secrets
                  key: oidc-client-id
            - name: CODER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: coder-secrets
                  key: oidc-client-secret
          ingress:
            enable: true
            host: ide.gsingh.io
            tls:
              enable: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
