{{- if .Values.ghost.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: ghost
    targetRevision: {{.Values.ghost.version}} 
    helm:
      values: |
        ghostHost: {{.Values.ghost.ghostHost}}
        ingress:
          enabled: true
          hostname: {{.Values.ghost.ingress.hostname}}
        ghostUsername: gurbakhshish
        existingSecret: ghost-secrets
        ghostEmail: {{.Values.ghost.ghostEmail}}
        ghostBlogTitle: Gurbakhshish's Blog
        mysql:
          enabled: false
        externalDatabase:
          host: 192.168.20.96
          user: ghostuser
          database: ghostdb
          existingSecret: ghost-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
