apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: ghost
    targetRevision: 19.8.7
    helm:
      values: |
        ingress:
          enabled: true
          hostname: blog.gsingh.io
        ghostUsername: gurbakhshish
        ghostEmail: hello@gsingh.io
        existingSecret: ghost-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true