apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proton-bridge
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts
    chart: protonmail-bridge
    targetRevision: {{.Values.proton-bridge.version}}
    helm:
      values: |
        env:
          TZ: "America/New_York"
        service:
          main:
            type: NodePort
            ports:
              imap:
                enabled: true
                protocol: TCP
                port: 143
                nodePort: 30143
              smtp:
                enabled: true
                protocol: TCP
                port: 25
                nodePort: 30025
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
