apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proton-bridge
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts
    chart: protonmail-bridge
    targetRevision: 5.4.2
    helm:
      values: |
        env:
          TZ: "America/New_York"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
