{{- if .Values.redpanda.enabled }}
{{- $redpanda := .Values.redpanda }}
{{- $redpandaImage := $redpanda.image | default dict }}
{{- $redpandaOperatorImage := $redpanda.operatorImage | default dict }}
{{- $redpandaConsole := $redpanda.console | default dict }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: {{ .Values.argocdNamespace | default "default" }}
  name: redpanda
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.redpanda.com/
    chart: redpanda
    targetRevision: {{ $redpanda.version | quote }}
    helm:
      values: |
        image:
          repository: {{ $redpandaImage.repository | default "docker.redpanda.com/redpandadata/redpanda" }}
          tag: {{ $redpandaImage.tag | default "v25.3.10" | quote }}
        {{- if $redpanda.imagePullSecrets }}
        podTemplate:
          spec:
            imagePullSecrets:
              {{- range $redpanda.imagePullSecrets }}
              - name: {{ . }}
              {{- end }}
        {{- end }}
        console:
          enabled: {{ $redpandaConsole.enabled | default false }}
        auth:
          sasl:
            enabled: false
        tls:
          enabled: false
        external:
          enabled: false
          service:
            enabled: false
        tuning:
          tune_aio_events: false
        statefulset:
          replicas: 1
          sideCars:
            image:
              repository: {{ $redpandaOperatorImage.repository | default "docker.redpanda.com/redpandadata/redpanda-operator" }}
              tag: {{ $redpandaOperatorImage.tag | default "v25.3.2" | quote }}
        listeners:
          kafka:
            port: 9092
          schemaRegistry:
            enabled: true
            port: 8081
          http:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $redpanda.namespace | default "data-platform" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
