apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/singh-gur/helm_charts.git
    path: charts/root-app/
    targetRevision: HEAD
    # secretRef:
    #   secretName: argo-ssh-key
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true