# Dagster PostgreSQL Secret
# Create this secret before deploying Dagster with external PostgreSQL
#
# Prerequisites:
#   1. Create PostgreSQL database:
#      CREATE DATABASE dagster;
#      CREATE USER dagster WITH PASSWORD 'your-secure-password';
#      GRANT ALL PRIVILEGES ON DATABASE dagster TO dagster;
#
#   2. Create this secret in the dagster namespace
#
# Create with kubectl:
#   kubectl create secret generic dagster-postgresql-secret \
#     --from-literal=postgresql-password="your-secure-password" \
#     -n dagster
---
apiVersion: v1
kind: Secret
metadata:
  name: dagster-postgresql-secret
  namespace: dagster
  labels:
    app.kubernetes.io/name: dagster
    app.kubernetes.io/instance: dagster
type: Opaque
stringData:
  postgresql-password: PASSWORD_HERE
