---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-oidc-secret
  namespace: data-platform
  labels:
    app.kubernetes.io/name: datahub
    app.kubernetes.io/instance: datahub
type: Opaque
stringData:
  client-secret: CLIENT_SECRET_HERE
