---
apiVersion: v1
kind: Secret
metadata:
  name: datahub-postgres-credentials
  namespace: data-platform
  labels:
    app.kubernetes.io/name: datahub
    app.kubernetes.io/instance: datahub
type: Opaque
stringData:
  postgres-password: PASSWORD_HERE
