# Example OAuth2 Proxy Secret
# DO NOT COMMIT THIS FILE WITH REAL CREDENTIALS
# This is a template showing the required structure

apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-dagster-secret
  namespace: dagster
type: Opaque
stringData:
  # Your OAuth2 Client ID from your IDP
  client-id: "YOUR_CLIENT_ID_HERE"
  
  # Your OAuth2 Client Secret from your IDP
  client-secret: "YOUR_CLIENT_SECRET_HERE"
  
  # Random 32-byte string for cookie encryption
  # Generate with: openssl rand -base64 32 | head -c 32
  cookie-secret: "GENERATE_RANDOM_32_BYTE_STRING"
