---
apiVersion: v1
kind: Secret
metadata:
  name: polaris-db-credentials
  namespace: data-platform
  labels:
    app.kubernetes.io/name: polaris
    app.kubernetes.io/instance: polaris
type: Opaque
stringData:
  username: polaris
  password: PASSWORD_HERE
  jdbcUrl: "jdbc:postgresql://192.168.2.119:5432/polaris"
