# Sample Kubernetes Secret for Zitadel Configuration
# This secret contains the Zitadel configuration including database credentials
#
# The config.yaml key contains the full Zitadel configuration in YAML format
# This allows you to configure database connections, SMTP, and other settings
# without exposing credentials in the Helm values
#
# Apply with: kubectl apply -f samples/zitadel-secrets.yaml -n <namespace>
#
# Reference: 
# - https://zitadel.com/docs/self-hosting/manage/configure
# - https://github.com/zitadel/zitadel-charts/tree/main/examples/3-referenced-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-secrets
  labels:
    app: zitadel
    component: config
type: Opaque
stringData:
  config.yaml: |
    # Database configuration
    Database:
      Postgres:
        # Database host (can be external PostgreSQL server)
        Host: postgres-host.example.com
        Port: 5432
        Database: zitadel
        
        # Connection pool settings
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        
        # User credentials for Zitadel application
        User:
          Username: zitadel
          Password: "your-zitadel-db-password-here"
          SSL:
            # Options: disable, require, verify-ca, verify-full
            Mode: require
        
        # Admin credentials for database setup/migrations
        Admin:
          Username: postgres
          Password: "your-postgres-admin-password-here"
          SSL:
            Mode: require
    
    # Optional: SMTP configuration for email notifications
    # Uncomment and configure if you want to enable email features
    # ExternalSecure: true
    # ExternalPort: 443
    # SMTPConfig:
    #   SMTP:
    #     Host: smtp.example.com:587
    #     User: noreply@example.com
    #     Password: "your-smtp-password-here"
    #   TLS: true
    #   From: noreply@example.com
    #   FromName: "Zitadel"
    
    # Optional: Twilio configuration for SMS
    # Twilio:
    #   SID: "your-twilio-sid"
    #   Token: "your-twilio-token"
    #   SenderNumber: "+1234567890"
    
    # Optional: Log level configuration
    # Log:
    #   Level: info  # Options: debug, info, warn, error
    #   Formatter:
    #     Format: text  # Options: text, json
