argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

  global:
    domain: argocd.gsingh.io
  server:
    ingress:
      enabled: true
      tls: false

  configs:
    params:
      server.insecure: true
