argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  ingress:
    enabled: true
    paths:
      - /argo-cd
  server:
    extraArgs:
      - --insecure
