argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

  server:
    ingress:
      enabled: true
      paths:
        - /argo-cd
    configs:
      params:
        server.insecure: true
