argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

  server:
    ingress:
      enabled: true
      hosts:
        - argocd.gsingh.io
        - argo.gursingh.com
  configs:
    params:
      server.insecure: true
