apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami

spec:
  rules:
    - host: whoami.gursingh.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 5678
